### ISSUE TITLE
Atlas location

### ISSUE THREAD

**Issue by chrisfilo** [rii-mango/Papaya#10]
Is there a way (preferably through params not compilation) to specify where Papaya should be looking for the atlas? I have multiple viewers on different URLs and I would like all of them to share one atlas.

**Comment by rii-mango** [comment]
You should now be able to set a parameter like so:

`params["atlasURL"] = "../myAtlasLocation/myAtlas.nii.gz";`

This assumes you have first used the `-atlas` parameter when building Papaya so that the labels are then added to papaya.js.  This parameter will then let you override the default location of the atlas image file.
