### ISSUE TITLE
How to set two papaya viewers that can be controlled by each window?

### ISSUE THREAD

**Issue by LiCong1992** [rii-mango/Papaya#141]
Hi guys,
Thanks for your project! It's really awesome! I'm quiet new to this and have a question that may be be amateur to ask. 
So my use case is that I have a two phase enhanced CT (arterial and venous phase) and I want to show axial view of both phase in two separate viewers and link their control together (means that if you zoom or change to another axial slices, the other viewer apply the same changes as well). So how to make that happen?
BTW, I'm using vue and the two viewer is instantiated as objects.

**Comment by crysta-l** [comment]
hi, i'm use this lib for mpr in vue but it doesn't work。
![image](https://user-images.githubusercontent.com/7333148/60227425-db7ca580-98c1-11e9-9d77-53078e0dcc5f.png)


![image](https://user-images.githubusercontent.com/7333148/60227437-e7686780-98c1-11e9-9097-fcd2ea61e26f.png)

could you tell me how can i import this lib correctly so that i can use it

**Comment by rii-mango** [comment]
This feature is available in Mango - https://mangoviewer.com
But it is not supported in Papaya.
