### ISSUE TITLE
Compatibility issues with recent Chrome

### ISSUE THREAD

**Issue by chrisfilo** [rii-mango/Papaya#23]
In Chrome version 43.0.2357.10

	'CanvasRenderingContext2D.webkitImageSmoothingEnabled' is deprecated. Please use 'CanvasRenderingContext2D.imageSmoothingEnabled' instead.

**Comment by rii-mango** [comment]
Both `webkitImageSmoothingEnabled` and `imageSmoothingEnabled` are being set, so the deprecation shouldn't affect the feature.  Unfortunately, since Safari still uses `webkitImageSmoothingEnabled`, I can't remove it (and property `imageSmoothingEnabled` appears to be defined even if the browser is not using it yet, so a simple check to see if that property exists won't work).  

So we'll just have to live with this annoying warning for now...
