### ISSUE TITLE
Dynamic file loading

### ISSUE THREAD

**Issue by jeansaigne** [rii-mango/Papaya#26]
Hi,
My goal is to display several overlays on the same image, but not at start, i want to let the user pick which overlay he wants to load and see, without reloading images. The amount of overlays can be high and thats why i can't permit myself to load them all at start.

#### Question : Is there a way to add a new overlay dynamically

**Comment by rii-mango** [comment]
Sorry for the late reply.  Yes, you can add files dynamically (not at startup).  Use the papaya-builder.sh to do this.  For example:

```./papaya-builder.sh -images overlay1.nii.gz overlay2.nii.gz overlay3.nii.gz ```

This will add options to the File menu for adding each overlay when selected.  Note that there is a hard-coded maximum number of overlays allowed.

```papaya.viewer.Viewer.MAX_OVERLAYS = 8;```

This can be changed in viewer.js.  I wanted to set some reasonable maximum to avoid performance issues, but you can change it.  Let me know if this doesn't solve your issue.

**Comment by dgutman** [comment]
I am looking into something similar, but want to be able to add and/or remove images through the javacsript API....

I think the 8 image max limit is reasonable, but I am curious if / how something like this could be done:

Say I have a stack of nifti images,  1st image is the base image, and the other 20 are masks/functional overlays.    By default it only loads the first image, but then 

1) use  javascript to load 7 more images ( I think I figured out how to do this..)

2)  I then have now hit the "cap".. so I want to say delete the first five masks, keep masks 6-8, and then load another 5 "new" files onto the viewer...  I am not sure if this is possible and also how the indexing would work..

So imagine file structure like this (I'll pretend the cap is 3 images instead of 8, but same idea)

nL = Not loaded initially

imageName   idxInArray   InitialIdxinPapaya
T1_baseImg      0              0
maskA               1              1
maskB               2              2
maskC               3              nL
maskD               4              nL

So can I "unload" maskA, and then load maskC dynamically..
if so, how does the indexing work in papaya...  would maskB maintain the index of 2, or since I would first remove maskA (papayaIndex1) would maskB's index within Papaya remain the same, or would this change as well?

I'm working on a parallel UI to help me control/toggle images, and trying to work through how to manage this.

**Comment by martinezmj** [comment]
When you add a new image, it always adds it to the top.  If you need to remove multiple overlays at once, you can call papaya.Container.removeImage(0, 1) repeatedly.  I just added a callback for individual image loading, so now you can do something like this:

```
papaya.Container.addImage(0, "data/zstat1.nii.gz", {"zstat1.nii.gz" : {
    loadingComplete: function {
        console.log("overlay loaded");
    }
}});
```

If you needed to load multiple overlays, just string them together using the callback.
