### ISSUE TITLE
Layout changes for portrait monitor

### ISSUE THREAD

**Issue by idmpacs** [rii-mango/Papaya#30]
Is there any way I can change layout to suit portrait monitor ?

**Comment by rii-mango** [comment]
This isn't a feature yet, but I think this would be useful.  That is, providing an option to move the smaller slice views beneath the main slice, instead of on the side.  I'll look into adding this feature.

Currently, the closest thing there is is to turn off orthogonal display.  This will result in the two smaller slice views being hidden, which might fit better on portrait display.

`params['orthogonal'] = false;`

**Comment by idmpacs** [comment]
Please look into adding this feature.

**Comment by rii-mango** [comment]
I've added support for this: `params['orthogonalTall'] = true;`

<img width="312" alt="screen shot 2016-01-19 at 3 16 09 pm" src="https://cloud.githubusercontent.com/assets/1859709/12432643/03c7ce3a-bec2-11e5-9f87-dc16e3c1d795.png">


I won't be able to upload a new build to the release folder until tomorrow, but the code is currently checked in.
