### ISSUE TITLE
Weird fringing artifact with parcellation maps

### ISSUE THREAD

**Issue by chrisfilo** [rii-mango/Papaya#39]
I have problems displaying this map: https://www.dropbox.com/s/2ig8llrzo64xfrv/Screenshot%202015-12-10%2016.37.16.png?dl=0

<img width="643" alt="screenshot 2015-12-10 16 37 16" src="https://cloud.githubusercontent.com/assets/238759/11729265/6ab61dac-9f5c-11e5-9fdf-5a3f91a8a0d3.png">

There appear to be fringes/borders on edges of the parcels. However when I view the same map in mango it looks correct:

<img width="333" alt="screenshot 2015-12-10 16 40 53" src="https://cloud.githubusercontent.com/assets/238759/11729355/cfd73176-9f5c-11e5-83c5-c46978547de9.png">

I've tried to turn off smoothing, but it did not change anything. You can download the map here:
http://neurovault.org/media/images/1003/brain_parcellation_mcinet_basc_asym_111clusters.nii.gz

PS other parcelation maps in NeuroVault are rendered correctly. For example: http://neurovault.org/images/1700/

**Comment by rii-mango** [comment]
Try again.  It should be fixed now.  The weird edges were caused by interpolation in the overlay.  The intended behavior was for interpolation to be turned off when smoothing is off -- that's how Mango works.  So that part has been fixed.

If you happen to want to leave smooth display on (e.g., for the underlay), you can also now specify 'interpolation' as true or false for that overlay.

I think the reason the other map you linked do didn't show the artifact is that the overlay dimensions were an exact multiple of the underlay, resulting in no interpolation.

A related item is that turning gradation off in the color tables is now supported.  That is, you can now create a color table like this:

`params["luts"] = [{"name": "Custom", "gradation":false, "data":[[0, 1, 0, 0], [.5, 1, 1, 0], [1, 1, 1, 1]]}];`

Normally the space between the color table "knots" is interpolated, but when setting "gradation" to false, it remains a solid color.  These types of color tables might be useful for segmented data.

**Comment by chrisfilo** [comment]
Great! Works!

**Comment by pangyuteng** [comment]
Super helpful post! Thank you both!!
Of note. segmentation data is better rendered at image space (`params["worldSpace"]=false;`)

Sample snippet for those that are visiting this page.
```
        var params = [];
        params["images"] = ["image.nii.gz","mask.nii.gz"];
        params["smoothDisplay"] = false;
        params["interpolation"] = false;
        params["worldSpace"] = false;
        params["kioskMode"] = false;
        params["luts"] = [{
            "name": "Custom",
            "gradation": false,
            "data": [[0, 1, 1, 1],[0.24, 1, 0, 0],[0.49, 0, 1, 0],[0.74, 0, 0, 1],[0.99, 1, 1, 0],[1, 1, 1, 0]],
            //"data": [[0, 1, 1, 1],[0.25, 1, 0, 0],[0.5, 0, 1, 0],[0.75, 0, 0, 1],[1, 1, 1, 0]],
        }];
        params["mask.nii.gz"] = {
            "lut": "Custom",
            "alpha": 0.5,
            "min": 0,
            "max": 4,
        };
        
```
world space:
![image](https://user-images.githubusercontent.com/5231403/225158769-67ecfbd6-621f-4f1e-8653-1e0d4b6b70fd.png)

image space:
![image](https://user-images.githubusercontent.com/5231403/225159021-a087e941-6e0b-49a1-b011-5e6b1f20076f.png)
