### ISSUE TITLE
Slow increment slice with mouse scroll

### ISSUE THREAD

**Issue by jongo** [rii-mango/Papaya#50]
When you move crosshairs, slice changing is really fast, but with mouse scrolling it is slow. Usually, user positions crosshair on ROI and then scrolls either with mouse or scrollbar. Is it possible to make it faster or give me hint where to change it?

Thanks

**Comment by rii-mango** [comment]
The slowness came from trying to make a smoother zoom scroll.  The unintended consequence was a much slower slice scroll.  I think it should be improved now.  Please try again.  

(The method that handles this is in src/utilities/platform-utils:`papaya.utilities.PlatformUtils.getScrollSign()`)

**Comment by jongo** [comment]
Hi, thanks for improvements. It is better now, but it is still feeling unresponsive. When you scroll mouse there is a lag before slice is changed.

**Comment by rii-mango** [comment]
I made some more changes, hopefully improvements.  It is really hard to normalize scrolling across browsers and devices.  The delta values returned from scrolling vary drastically (like orders of magnitude) across the spectrum of OS/browser/devices.

Chrome and Safari seem to be over sensitive, while Firefox and IE seem to be under sensitive.  IE seems to still be performing worst in terms of responsiveness, but I can't tell for sure since I'm running it in a VM and testing with a Mac mouse.

Are these changes any better or worse?  What browser and OS are you testing in?

**Comment by jongo** [comment]
Hi, thanks for fix. It is better now. I am using Google Chrome 49.0.2623.110 and Windows 7 64. I also tested this fix in Firefox and IE. Firefox works also great, IE is more sluggish, but not a big deal.
