### ISSUE TITLE
Is there a way to control how the interface is displayed?

### ISSUE THREAD

**Issue by chrisfilo** [rii-mango/Papaya#6]
Could I for example turn of the toolbar and the two slice viewers on the right? How could I do this?

**Comment by rii-mango** [comment]
> Wouldn't it be easier to have one image with a two colour map?

You can now set `combineParametric` (global parameter) to true to collapse the button/menu into one, when loading parametric overlays (see screenshot below).

Also, there are a few new UI options:

`showControls` (this is true by default) -- this will display overlaid increment/decrement, swap main slice and goto origin and center buttons (some buttons will be hidden if the viewer is not big enough)

`showControlBar` -- if true (and also `showControls` is true) the control buttons will be displayed as a bar beneath the viewer.  If you combine this with `kioskMode`, the image button/menus will appear there in the control bar as well.

![screen shot 2015-07-09 at 9 51 49 am](https://cloud.githubusercontent.com/assets/1859709/8598451/63448d7a-2620-11e5-8e35-ea78668c0d76.png)

This issue is pretty old, so i'm not sure if you are still actively using Papaya -- but if so, let me know if this addresses the issues you had or if there are still some things you'd like to see.
