### ISSUE TITLE
Synchronous creation

### ISSUE THREAD

**Issue by rdevon** [rii-mango/Papaya#60]
Small issue when loading data synchronously and forming papaya objects:

	d3.json("images/data.json", function(error, data) {
		if (error) throw error;
		var images = data.images; // array of file paths (not used in this example).

		var params = {
			worldSpace: true,
			kioskMode: true,
			showControls: false,
			showImageButtons: false,
			fullScreenPadding: false
		};

		d3.select(".row").selectAll(".papaya-viewer")
			.data(images).enter()
			.append("div")
			.attr("class", "col-xs-6 col-sm-3 col-md-3 well rowCell")
			.append("div")
			.attr("class", "papaya")
			.attr("data-params", "params");

		images.forEach( function (d, i) {
			papaya.Container.resetViewer(i, params);
		});
	});

When forming the papaya objects synchronously in this manner, each of the divs print out "`papaya requires javascript...`". (I imagine the result will be the same if jQuery ajax is used). If this is done outside of d3.json (such as using a dummy array as data), it works fine.
Is there a way around this or do the papaya objects need to be formed asynchronously?

Thanks

**Comment by rii-mango** [comment]
The "Papaya requires JavaScript..." message happens when JavaScript doesn't run for some reason.  That is, the message is part of the CSS (src/css/base.css) and is removed by JavaScript (src/js/main.js#resetComponents).  So if JavaScript never runs, the message just stays there.

If you can create a little working example that I can play with, I can get a better idea of what might be going on (maybe just a simplified HTML for the JS you posted).  

It should be able to support synchronous and asynchronous loading -- but maybe something else is needed to support libraries like D3.

**Comment by kaustubhrpatil** [comment]
Has this been solved?

I encountered the same issue recently.

Thanks
