### ISSUE TITLE
can't get uncompressed js file

### ISSUE THREAD

**Issue by fancyoung** [rii-mango/Papaya#72]
I wanner debug papaya.js in console, but the js file is compressed.
There is no way to get uncompressed file through config build file.

**Comment by fancyoung** [comment]
I add a new argument `nocompress` in Papaya-Builder, and udpate the papaya-builder.sh, should I send a pull request?

**Comment by rii-mango** [comment]
There are a couple of files in the project test directory that are useful for debugging: debug_local.html and debug_server.html.  These contain references to the project's uncompressed source files, rather than papaya.js.

Use debug_server.html if you can put the files in a webserver space.  (I use WebStorm IDE for development, which contains a built-in webserver at http://localhost:63342/.)  If you don't have a server available, you can use debug_local.html, but in this case you won't be able to give it image URLs.

**Comment by fancyoung** [comment]
Thanks, it's helpful.
