### ISSUE TITLE
Integrating Papaya with Cornerstone

### ISSUE THREAD

**Issue by ali-muhammad** [rii-mango/Papaya#74]
Hey, 

I have been using cornerstone in my application, since papaya provides more great features so I want to integrate papaya with cornerstone. 

Can you please tell me is there a way to integrate these 2 viewers ?

**Comment by martinezmj** [comment]
It should be possible, but would require a little work.  Papaya's DICOM support comes from [Daikon](https://github.com/rii-mango/Daikon).  Daikon is added to Papaya as a library (see lib/ folder), then it is "wrapped" in js/volume/dicom/header-dicom.js.

It should be possible to replace Daikon with Cornerstone by just implementing the same functions in header-dicom.js replacing any reference to `daikon` with something comparable from Cornerstone.

**Comment by ali-muhammad** [comment]
Thanks a lot for quick reply @martinezmj . I haven't tried it yet but i'll let you know when I'll get this done.

**Comment by FredLoney** [comment]
We evaluated Cornerstone and Papaya for a QIN project at OHSU, and selected Papaya for its UI functionality, quality and NIfTI support.

It would be helpful to understand what is meant by "integrate papaya with cornerstone". It is unclear, e.g., what benefit comes from replacing the Papaya DICOM reader with the Cornerstone DICOM reader. Cornerstone makes a point of being agnostic with respect to image transport and parsing, delegating to an [image loader](https://github.com/chafey/cornerstone/wiki/ImageLoader) plug-in instead. The Cornerstone DICOM reader is a small, separate [library](https://github.com/chafey/dicomParser).

However, I doubt if that is what you have in mind for integration. More useful would be a port of the Papaya UI as a [Cornerstone Tool](https://github.com/chafey/cornerstoneTools). We investigated that alternative, but it would be a substantial undertaking that would be incompatible with the Papaya source.

Papaya and Cornerstone are two alternative image viewer frameworks. Papaya has useful functionality, but is not modularized into easily adapted web components. Cornerstone has a modular architecture, but so far has limited functionality and has its own integration issues.

We had to make significant source code modifications to both libraries to get them to work with our web application. I will post the Papaya limitations as a separate issue in the future, hopefully by February 2017. In the meantime, I'd be curious what you discover in your integration effort.

**Comment by chrischang005** [comment]
I already implement it as a jump button in cornerstone tools. The only issue is that the request result from cornerstone WADOimageloader  can't be recognized by papaya. 
The array buffer I got cant be loaded as instruction in config. I mentioned this at https://github.com/rii-mango/Papaya/issues/89#issuecomment-321212310 Does it related to the difference between Dikon and cornerstone? How could I fix this? Any help would be appreciated. Thx in advance.

**Comment by FredLoney** [comment]
The cornerstone WADOimageloader result is an [Image](https://github.com/chafey/cornerstone/wiki/Image) object, not an array buffer. I don't understand what a "jump button" is, but if it is a button whose handler calls the image loader, sets the global `images` variable to the resolved promise result and starts Papaya within a DOM element, then you have some interface marshalling and screen management work ahead of you. You might consider a simple hyperlink to a new window under Papaya's control. However, there is still an interface mismatch problem because Papaya expects an image url in a global variable, not an arraybuffer.

As with Cornerstone, Papaya needs the image metadata, not just the raw pixels. If you are ambitious, you could contribute a Cornerstone -> Papaya image object adaptor with a more flexible Papaya image input mechanism. Preferably, Papaya would delegate to the Cornerstone image loader mechanism. That requires a fair amount of Papaya internals surgery. If you don't want to dive into Papaya internals, then you will need to make a binary Cornerstone vs Papaya choice, as I did.

**Comment by chrischang005** [comment]
Thank you very much for the quick reply. Sorry I didn't express it clear.
I did this because the [configuration page](https://github.com/rii-mango/Papaya/wiki/Configuration) says: 

> Images can also be referenced as files or raw data (ArrayBuffer). `var myBinaryDataRef = someBinaryData;
params["binaryImages"] = ["myBinaryDataRef"];`

This is how I implement it:
I dive into WADOimageloader. When the xhrrequest (XMLHttpRequest) is send to WADOserver(in my case, dcm4chee), I save the response(DICOM P10 instance, an arraybuffer) to the browser storage indexeddb. Then I call hyperlink at new window then load this arraybuffer as params["binaryImages"] above. It would be either a syntax error or "this format is not recognized". 
I'm pretty sure it's arraybuffer's problem because the same routine works for setting dicom files as params["image"].

Is this the same interface mismatch problem you mentioned? If I want this to work, which part of the daikon should I modify?

I'm vert grateful.

**Comment by FredLoney** [comment]
Ah, binaryImages is a new feature since I last visited Papaya. It appears that Papaya still expects you to provide the files or urls even when you set binaryImages. Papaya needs the headers and reads those from the files. binaryImages is a convenience which obviates Papaya reading the pixel array from the file. If this supposition is correct, then unfortunately a remote image header can only be obtained by transmitting the entire image file, so it doesn't buy you much.

**Comment by FredLoney** [comment]
Note that your hyperlink button is not Cornerstone view integration in the sense of this issue thread. Rather, it addresses the question "How do I open a new Papaya window on an image which is already loaded into the browser"?

**Comment by rii-mango** [comment]
Archiving this.  Out of scope for now.
