### ISSUE TITLE
World coordinates map to a different location in fsl and papaya viewer

### ISSUE THREAD

**Issue by amitvakula** [rii-mango/Papaya#77]
We click on a location in the papaya viewer, record the world coordinates, and navigate to the same spot in fslview. We found that the spots are in different locations. It seems like the affine transform encoded in the NIFTI file differs in behavior than the affine transformation used in the Papaya viewer for select images. Attached is a NIFTI that does just that and below are two images which demonstrate this point. Could you help us understand why Papaya maps the same world coordinates to completely different locations than FSLView? Specifically, we would appreciate if you could explain how we can ensure that the world coordinates we record in the papaya viewer map to the same location in the NIFTI when we open it in FSLView.

![screenshot from 2016-12-08 18-44-13](https://cloud.githubusercontent.com/assets/6167198/21036105/72e741e6-bd78-11e6-90d1-94552d050f5a.png)
![screenshot from 2016-12-08 18-47-53](https://cloud.githubusercontent.com/assets/6167198/21036106/7575fd94-bd78-11e6-9a4c-1063b9b3aa88.png)

[ples_lpa_mms575-mse4353-010-3d_FLAIR_iso_1_index.nii.gz](https://github.com/rii-mango/Papaya/files/641094/ples_lpa_mms575-mse4353-010-3d_FLAIR_iso_1_index.nii.gz)

**Comment by amitvakula** [comment]
To be a bit more specific, for the attached image, consider world coordinate: [4,17,-15]

in papaya the intensity is 8, in fslview view, intensity is 0 (note: we verified this on the demo http://rii.uthscsa.edu/mango/papaya/ as a sanity check)

**Comment by martinezmj** [comment]
The main issue stems from differences in the way FSLView and Mango/Papaya display their images.  This image contains an image transform.  FSLView displays the image untransformed but gives transformed coordinates.  Papaya transforms the image so that the coordinates are not.

That is, in FSLView if you pick an "axial" slice, say Z=-15, and drag your mouse across it, you expect the X and Y coordinates to change, not Z.  But in this case, Z will also change.

Whereas, in Papaya the image is transformed so that, using the same example, if you are on axial slice Z=-15 and drag your mouse across it, you stay on axial slice Z=-15.

So because Papaya transforms the image, you get some interpolation.  Where there may be 2 or 3 pixels of data in FSLView surrounded by zeros, you may get a few more pixels that contain data in Papaya because of the smoothing.  If there was no thresholding, this effect would be much less noticeable.

So neither way is wrong, it is just two different ways to look at the data.

One issue I did find though, which was a difference between Mango and Papaya, was that in Papaya even though the image display was interpolated as expected, if you loaded the image you attached as the base image (not overlay), then the value the coordinate display reported was not interpolated like the image.  I've fixed this in the most recent build [here](https://github.com/rii-mango/Papaya/tree/master/release/current).  

So in both Mango and Papaya the value reported at [4,17,-15] should be 6.082, which corresponds to the value of 8 reported at [3.91,16.74,-15.57) in FSLView.  (Again, the reason you get something less than 8 in Mango/Papaya, is because the image is both transformed and thresholded.)
