### ISSUE TITLE
Papaya reading directly a DICOM database

### ISSUE THREAD

**Issue by renardfe** [rii-mango/Papaya#89]
Hi,

I would like to know if it is possible to read a DICOM provided directly by a DICOM database (like Osirix). I imagine for exemple a WADO request (Web Access to Dicom Objects) to avoid to save temporary files from my DICOM database.

Thanks!
Best regards
Félix

**Comment by martinezmj** [comment]
As long as the WADO request is a URL that returns a DICOM image, yes it should work fine.

**Comment by chrischang005** [comment]
I got an arraybuffer of a CT slice from wado request then pass it to papaya like suggested in config part. However it raise up error "Cannot read property 'indexOf' of undefined".

I have checked the arraybuffer is complete, and the content is legal because I can use the original file on papaya.

Any clue on how this error arise? Thank you in advance

**Comment by FredLoney** [comment]
See also [Integrating Papaya with Cornerstone #74](https://github.com/rii-mango/Papaya/issues/74) follow-up comment.

**Comment by martinezmj** [comment]
@chrischang005 I've added [this example](https://github.com/rii-mango/Papaya/blob/master/tests/debug_server_arraybuffer.html) of how to load an image using an arraybuffer.
